In [1]:
import numpy as np
import torch

## Basic transpose etc.

### Using Numpy

In [6]:
arr = np.array([[1, 2, 3, 4]])
print(arr.T)

[[1]
 [2]
 [3]
 [4]]


### Using PyTorch

In [7]:
tens = torch.tensor([[1, 2, 3, 4]])
print(tens.T)

tensor([[1],
        [2],
        [3],
        [4]])


## Dot product

### Using Numpy

In [10]:
v = np.array([1, 2, 3, 4])
w = np.array([4, 8, 0, 2])

print(np.dot(v, w))

28


In [12]:
print(np.sum(v * w))

28


### Using PyTorch

In [13]:
t1 = torch.tensor([1, 4, 8, 22])
t2 = torch.tensor([8, 29, 21, 22])

print(torch.dot(t1, t2))
print(torch.sum(t1 * t2))

tensor(776)
tensor(776)


## Matrix multiplication

### Numpy

In [19]:
A = np.random.randn(3, 5)
B = np.random.randn(5, 7)
C = np.random.randn(3, 5)


A@B

array([[-0.59575448,  2.18803024,  0.73954035,  0.7589083 , -0.37843381,
         0.63356196, -0.86885267],
       [-1.67184557,  3.08467817,  1.68828045,  0.03884562, -0.80260636,
         2.51736859, -2.22338072],
       [-0.42916866,  3.13018839, -4.12652408, 12.2041686 ,  2.96158315,
        -4.24468675,  1.57889748]])

In [17]:
np.matmul(A, B)

array([[ 0.12393561,  3.34739576, -3.44410008, -0.05338881,  2.07444725,
         3.26380189, -0.60179909],
       [ 1.62806612, -0.47355965,  2.65546093,  0.8883373 , -1.53771339,
        -4.14363558, -1.51388246],
       [ 1.51833565, -3.34328002,  4.94034865, -1.87532111, -5.12561974,
        -3.86849887,  0.80991903]])

In [20]:
C.T@A # transpose of C multiplied with A

array([[ 1.4157245 , -0.1276071 ,  1.77000499,  2.74336253, -3.88827036],
       [ 0.26298928,  0.61402003,  0.56627091, -0.53612172, -0.90028038],
       [ 0.36204312,  0.64966508,  1.25488505,  0.87657669, -3.13002444],
       [-1.60857562,  1.7506655 ,  0.23319281, -1.86406993, -1.87263045],
       [ 0.11629011,  0.43944601,  0.5732266 ,  0.10192609, -1.36864638]])

### Use PyTorch

In [22]:
P1 = torch.randn(3, 4)
P2 = torch.randn(4, 5)
C1 = np.random.rand(4, 7) # is this dtype compatible with pytorch?
C2 = torch.tensor(C1, dtype=torch.float)

In [25]:
P1@C1 # wow this works natively but not always

tensor([[-0.4956, -1.5338, -1.2105, -1.1085, -1.0477, -1.0672, -1.7143],
        [-0.7367, -0.0933, -0.0828, -0.4978, -0.9621, -0.6894, -0.7147],
        [-1.4697, -1.1612, -0.4494, -0.9258,  0.8166, -0.4804, -1.8723]],
       dtype=torch.float64)

In [26]:
P1@C2

tensor([[-0.4956, -1.5338, -1.2105, -1.1085, -1.0477, -1.0672, -1.7143],
        [-0.7367, -0.0933, -0.0828, -0.4978, -0.9621, -0.6894, -0.7147],
        [-1.4697, -1.1612, -0.4494, -0.9258,  0.8166, -0.4804, -1.8723]])