In [1]:
import numpy as np
import torch

In [2]:
v = np.array([ 1,40,2,-3 ])

In [3]:
print(np.min(v))
print(np.max(v))

-3
40


# But what is the position of the max and min values

In [22]:
print(np.argmin(v))
print(np.argmax(v))

3
1


# now let's try matrices instead of vectors

In [23]:
M = np.array([ [0,1,10], [20,8,5] ])

In [24]:
np.min(M)

0

In [25]:
np.max(M)

20

In [26]:
np.argmin(M)

0

In [27]:
np.argmax(M)

3

## So it linearizes the entire thing in one dimension and gives us the index in that data structure

### But if we wanted a particular axis; Axis corresponds to dimension so axis=0 means column axis=1 means across rows

In [28]:
np.min(M, axis=0) # It'll give minimum in each column but you're going to move per row

array([0, 1, 5])

In [29]:
np.min(M, axis=1) # so basically it'll give all minimums in each row but moving across columns

array([0, 5])

### Let's try argmin and argmax

In [30]:
np.argmin(M, axis=0)

array([0, 0, 1])

In [31]:
np.argmin(M, axis=1)

array([0, 2])

In [32]:
# Let's try pytorch

In [35]:
torch.argmin(torch.Tensor([1, 40, 2 -3]))

tensor(2)

In [36]:
torch.argmin(torch.Tensor([1, 40, 2, -3]))

tensor(3)

In [44]:
PM = torch.tensor([
    [0, 1, 10], 
    [20, 8, 5]
])

In [39]:
torch.min(PM)

tensor(0)

In [46]:
min2 = torch.min(PM, axis=0) # axis = 0 means go row by row but for every column


### Moment you start giving it axis it'll start returning indices for the corresponding values

In [47]:
print(min2)

torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))


In [48]:
type(min2)

torch.return_types.min

In [49]:
min2.values

tensor([0, 1, 5])

In [50]:
min2.indices

tensor([0, 0, 1])