# Seeding a Random process using Numpy and PyTorch

In [1]:
# Can reproduce model based on random seed

In [2]:
import numpy as np
import torch

In [22]:
np.random.seed(17)
print(np.random.randn(2, 5))
print(np.random.randn(2, 5))

# [[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
#  [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]]
# [[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
#  [-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]]


[[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
 [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]]
[[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
 [-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]]


## Another way to set the seed is through RandomState class

In [8]:
random_seed1 = np.random.RandomState(17)
random_seed1.randn(2, 5)

array([[ 0.27626589, -1.85462808,  0.62390111,  1.14531129,  1.03719047],
       [ 1.88663893, -0.11169829, -0.36210134,  0.14867505, -0.43778315]])

In [9]:
random_seed1.randn(2, 5)

array([[ 2.171257  ,  1.15231025, -1.81881234, -0.13804934,  0.53983961],
       [-1.77528229,  1.31487654, -0.47344805, -1.0922299 , -0.25002744]])

In [10]:
# But if you initialize all of the seeds in one cell. Subsequent invocations are always going to be the same

In [17]:
random_seed1 = np.random.RandomState(17)
print(random_seed1.randn(2, 5))
print(random_seed1.randn(2, 5))

# [[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
#  [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]]
# [[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
#  [-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]]

[[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
 [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]]
[[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
 [-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]]


## RANDOMSTATE IS BETTER

In [24]:
torch.randn(5)

tensor([-1.6809, -0.4839, -0.1557,  0.8893, -0.0290])

In [31]:
torch.manual_seed(17)
print(torch.randn(5))
print(np.random.randn(5))

# tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
# [-0.9822943   1.03126909  0.49133378 -0.4466466  -0.80636008]

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.97754176 -0.13858525  0.10385631  0.30059104  0.9682053 ]


## TORCH SEED IS LOCALIZED TO PYTORCH